spring:
  application:
    name: cardex-property-access-service
  config:
    import: "optional:configserver:"
  profiles:
    active: dev

server:
  port: ${port:8100}


management:
  endpoints:
    web:
      exposure:
        include: refresh